source 'http://172.16.69.171/ios/iosspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_modular_headers!
inhibit_all_warnings!

platform :ios, '10.0'


target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

end
